### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by parzivalishan** [kemitchell/vesting-implement.js#1]
i am trying to clone your vesting-implement and do some changes to see , i have creating a similar vesting.js file and vesting-implement.js for testing 

but i am unable to see my vesting-implement..js have dependency of my first file ishanvesting.js

first repo  - https://github.com/parzivalishan/ishanvesting.js

second repo- https://github.com/parzivalishan/vesting-implement.js

second file dependecy section - https://github.com/parzivalishan/vesting-implement.js/network/dependencies

can you please let me know why my first repo is not in the dependency of the second repo

**Comment by kemitchell** [comment]
I am glad you find this very old repo interesting, but I am not going to debug your own code for you.

**Comment by parzivalishan** [comment]
alright
